# Generated by Django 5.2.14 on 2026-07-06 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_options_alter_payment_amount_and_more'),
        ('users', '0003_center_user_center'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='received_by',
        ),
        migrations.AddField(
            model_name='payment',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='users.center'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Накд'), ('transfer', 'Перевод')], default='cash', max_length=10, verbose_name='Тарз'),
        ),
    ]
