# Generated by Django 5.2.14 on 2026-07-06 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_group_center_group_created_at_alter_group_price_and_more'),
        ('students', '0002_alter_student_options_alter_student_balance_and_more'),
        ('users', '0003_center_user_center'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Хонанда', 'verbose_name_plural': 'Хонандагон'},
        ),
        migrations.AddField(
            model_name='student',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='users.center'),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='groups.group', verbose_name='Гурӯҳ'),
        ),
        migrations.AlterField(
            model_name='student',
            name='start_date',
            field=models.DateField(auto_now_add=True, verbose_name='Таърихи қайд'),
        ),
    ]
