# Generated by Django 5.2.14 on 2026-05-21 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Гурӯҳ', 'verbose_name_plural': 'Гурӯҳҳо'},
        ),
        migrations.AlterField(
            model_name='group',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Фаъол'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Номи гурӯҳ'),
        ),
        migrations.AlterField(
            model_name='group',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Нарх'),
        ),
        migrations.AlterField(
            model_name='group',
            name='room',
            field=models.CharField(blank=True, max_length=50, verbose_name='Кабинет'),
        ),
        migrations.AlterField(
            model_name='group',
            name='schedule',
            field=models.CharField(max_length=200, verbose_name='Вақт'),
        ),
        migrations.AlterField(
            model_name='group',
            name='subject',
            field=models.CharField(max_length=100, verbose_name='Фан'),
        ),
        migrations.AlterField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_groups', to=settings.AUTH_USER_MODEL, verbose_name='Муаллим'),
        ),
    ]
