# Generated by Django 5.2.14 on 2026-05-21 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('groups', '0002_alter_group_options_alter_group_is_active_and_more'),
        ('students', '0002_alter_student_options_alter_student_balance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'Давомот', 'verbose_name_plural': 'Давомот'},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(verbose_name='Сана'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='groups.group', verbose_name='Гурӯҳ'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='late_minutes',
            field=models.IntegerField(default=0, verbose_name='Дақиқаи дер'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='note',
            field=models.TextField(blank=True, verbose_name='Шарҳ'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Омад'), ('absent', 'Наомад'), ('late', 'Дер кард'), ('excused', 'Сабаби эҳтиромнок')], default='present', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.student', verbose_name='Хонанда'),
        ),
    ]
