# Generated by Django 5.2.14 on 2026-07-06 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_options_alter_attendance_date_and_more'),
        ('users', '0003_center_user_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='users.center'),
        ),
    ]
